registry-datavolume:
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.container.hostname_override: container_name
  entrypoint:
  - /bin/true
  image: busybox
  volumes:
  - /data/registy
  net: none
