registry-datavolume:
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.container.hostname_override: container_name
  entrypoint:
  - /bin/true
  image: busybox
  volumes:
  - /data/registy
  net: none

registry:
  restart: always
  image: registry:latest
  ports:
    - ${PORT}:5000
  tty: true
  stdin_open: true
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes_from:
    - registry-datavolume
  labels:
    io.rancher.container.pull_image: always
    io.rancher.sidekicks: registry-datavolume
    io.rancher.container.hostname_override: container_name