registry-datavolume:
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.container.hostname_override: container_name
  entrypoint:
    - /bin/true
  image: busybox
  volumes:
    - /var/lib/registry
  net: none

registry:
  restart: always
  image: registry:2.4
  ports:
    - ${PORT}:5000
  tty: true
  stdin_open: true
  volumes_from:
    - registry-datavolume
  labels:
    io.rancher.container.pull_image: always
    io.rancher.sidekicks: registry-datavolume
    io.rancher.container.hostname_override: container_name