name: Docker Registry
description: |
  It will install the docker registry frontend by konradkleine and the registry as a sidekick.
  The registry can be accessed directly via the frontend.
version: v0.1.0
category: Continuous Integration
maintainer: Daniel Sailer
projectURL: |
  https://docs.docker.com/registry/deploying/
  https://docs.docker.com/registry/
  https://hub.docker.com/r/konradkleine/docker-registry-frontend/
  https://github.com/kwk/docker-registry-frontend/tree/v2
