name: Docker Registry
description: |
  It will install the docker registry frontend by konradkleine and the latest official docker registry as a sidekick.
  The registry can be accessed directly via the frontend.
version: v0.1.0
category: Continuous Integration
maintainer: Daniel Sailer
projectURL: https://hub.docker.com/r/konradkleine/docker-registry-frontend/
